In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Reading the csv file and putting it into 'df' object.
df = pd.read_csv('Moovie_type.csv')
df

Movie  no of kicks  no of kisses type of movie
0     A            3           103       Romance
1     B            2           102       Romance
2     C            1            21       Romance
3     D          110            10        Action
4     E           60            10        Action
5     F          102             2        Action
6     G           20            70       Unknown

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,3], test_size = .25,random_state = 50)

In [5]:
X_train

Movie  no of kicks  no of kisses
4     E           60            10
1     B            2           102
3     D          110            10
6     G           20            70
0     A            3           103

In [6]:
X_test

Movie  no of kicks  no of kisses
2     C            1            21
5     F          102             2

In [7]:
y_train

4     Action
1    Romance
3     Action
6    Unknown
0    Romance
Name: type of movie, dtype: object

In [8]:
y_test

2    Romance
5     Action
Name: type of movie, dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder
# apply Label encoder to df_categorical

le = LabelEncoder()
df.iloc[:,3] = le.fit_transform(df.iloc[:,3])
df.head()

Movie  no of kicks  no of kisses  type of movie
0     A            3           103              1
1     B            2           102              1
2     C            1            21              1
3     D          110            10              0
4     E           60            10              0

In [10]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [11]:
X

array([[  3, 103],
       [  2, 102],
       [  1,  21],
       [110,  10],
       [ 60,  10],
       [102,   2],
       [ 20,  70]])

In [12]:
y

array([1, 1, 1, 0, 0, 0, 2])

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [14]:
y_pred = knn.predict(X)

In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y,y_pred))

0.7142857142857143


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .25,random_state = 50)

In [17]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
y_pred = knn.predict(X_test)

In [19]:
print(accuracy_score(y_test,y_pred))

0.5


In [20]:
from scipy.spatial import distance
distance.euclidean([0,0], [5,5])

7.0710678118654755

In [21]:
X_train.shape

(5, 2)

In [22]:
X_train[0], X_test[0]

(array([60, 10]), array([ 1, 21]))

In [23]:
X_train[0], X_train[1],X_train[2], X_train[3],X_train[4]


(array([60, 10]),
 array([  2, 102]),
 array([110,  10]),
 array([20, 70]),
 array([  3, 103]))

In [24]:
distances = []
for i in range(len(X_train)):
    d = distance.euclidean(X_train[i], X_test[0])
    distances.append(d)
distances

[60.01666435249463,
 81.00617260431454,
 109.55363982999378,
 52.55473337388365,
 82.02438661763951]

In [103]:
distances.sort()
distances

[904.6888968037576,
 2725.083851920891,
 3557.799600876924,
 4032.5210476822062,
 5820.533394801545,
 6266.696258795379,
 6878.086652550984,
 6931.858192432964,
 7078.810705196177,
 7134.980939007476,
 7333.421029778667,
 10622.235357964913]

In [106]:
y_pred = knn.predict(X_test[0].reshape(1,-1))

In [107]:
y_pred

array([1])

In [113]:
y_

15    1
12    1
14    1
3     2
2     2
Name: player type, dtype: int64