In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [114]:
# Reading the csv file and putting it into 'df' object.
df = pd.read_csv('cricketers.csv')
df

Player  Mat   Runs  Wkts  player type
0     A Kumble  271    938   334       Bowler
1    J Srinath  229    883   315       Bowler
2       Z Khan  200    792   269       Bowler
3      H Singh  234   1237   265       Bowler
4    Kapil Dev  225   3783   253  All Rounder
5     I Phatan  120   1544   173  All Rounder
6     R Jadeja  147   1990   171  All Rounder
7   Tendulkhar  463  18426   154      Batsman
8      R Shwin  111    675   150       Bowler
9      B Kumar  103    476   114       Bowler
10    Youvaraj  304   8701   110  All Rounder
11     Ganguly  308  11363   100      Batsman
12     Sehwagh  251   8273    94      Batsman
13    H Pandya   45    731    44  All Rounder
14     S Raina  226   5615    36      Batsman
15    R sharma  201   7808     8      Batsman
16   V Khohli   222  10533     4      Batsman

In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,4], test_size = .25,random_state = 50)

In [116]:
X_train

Player  Mat   Runs  Wkts
7   Tendulkhar  463  18426   154
9      B Kumar  103    476   114
8      R Shwin  111    675   150
10    Youvaraj  304   8701   110
5     I Phatan  120   1544   173
6     R Jadeja  147   1990   171
4    Kapil Dev  225   3783   253
1    J Srinath  229    883   315
13    H Pandya   45    731    44
11     Ganguly  308  11363   100
0     A Kumble  271    938   334
16   V Khohli   222  10533     4

In [117]:
X_test

Player  Mat  Runs  Wkts
15  R sharma  201  7808     8
12   Sehwagh  251  8273    94
14   S Raina  226  5615    36
3    H Singh  234  1237   265
2     Z Khan  200   792   269

In [119]:
y_train

7         Batsman
9          Bowler
8          Bowler
10    All Rounder
5     All Rounder
6     All Rounder
4     All Rounder
1          Bowler
13    All Rounder
11        Batsman
0          Bowler
16        Batsman
Name: player type, dtype: object

In [120]:
y_test

15    Batsman
12    Batsman
14    Batsman
3      Bowler
2      Bowler
Name: player type, dtype: object

In [118]:
from sklearn.preprocessing import LabelEncoder
# apply Label encoder to df_categorical

le = LabelEncoder()
df.iloc[:,4] = le.fit_transform(df.iloc[:,4])
df.head()

Player  Mat  Runs  Wkts  player type
0   A Kumble  271   938   334            2
1  J Srinath  229   883   315            2
2     Z Khan  200   792   269            2
3    H Singh  234  1237   265            2
4  Kapil Dev  225  3783   253            0

In [76]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [77]:
X

array([[  271,   938,   334],
       [  229,   883,   315],
       [  200,   792,   269],
       [  234,  1237,   265],
       [  225,  3783,   253],
       [  120,  1544,   173],
       [  147,  1990,   171],
       [  463, 18426,   154],
       [  111,   675,   150],
       [  103,   476,   114],
       [  304,  8701,   110],
       [  308, 11363,   100],
       [  251,  8273,    94],
       [   45,   731,    44],
       [  226,  5615,    36],
       [  201,  7808,     8],
       [  222, 10533,     4]])

In [78]:
y

array([2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 1, 1, 0, 1, 1, 1])

In [79]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [80]:
y_pred = knn.predict(X)

In [81]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y,y_pred))

0.8823529411764706


In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .25,random_state = 50)

In [83]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [84]:
y_pred = knn.predict(X_test)

In [85]:
print(accuracy_score(y_test,y_pred))

0.8


In [86]:
from scipy.spatial import distance
distance.euclidean([0,0], [5,5])

7.0710678118654755

In [95]:
X_train.shape

(12, 3)

In [89]:
X_train[0], X_test[0]

(array([  463, 18426,   154]), array([ 201, 7808,    8]))

In [96]:
X_train[0], X_train[1],X_train[2], X_train[3],X_train[4],X_train[5]
# 1. sachin , 2. B.Kumar, 3. R.Ashwin, 4. Yuvraj 5. I.Phatan, 6. R jadeja

(array([  463, 18426,   154]),
 array([103, 476, 114]),
 array([111, 675, 150]),
 array([ 304, 8701,  110]),
 array([ 120, 1544,  173]),
 array([ 147, 1990,  171]))

In [99]:
X_train[6], X_train[7],X_train[8], X_train[9],X_train[10],X_train[11]
# 1. kapildev , 2. J. srinath, 3. H pandya, 4.  5. Ganguly, 6. V Kohli

(array([ 225, 3783,  253]),
 array([229, 883, 315]),
 array([ 45, 731,  44]),
 array([  308, 11363,   100]),
 array([271, 938, 334]),
 array([  222, 10533,     4]))

In [101]:
distances = []
for i in range(len(X_train)):
    d = distance.euclidean(X_train[i], X_test[0])
    distances.append(d)
distances

[10622.235357964913,
 7333.421029778667,
 7134.980939007476,
 904.6888968037576,
 6266.696258795379,
 5820.533394801545,
 4032.5210476822062,
 6931.858192432964,
 7078.810705196177,
 3557.799600876924,
 6878.086652550984,
 2725.083851920891]

In [103]:
distances.sort()
distances

[904.6888968037576,
 2725.083851920891,
 3557.799600876924,
 4032.5210476822062,
 5820.533394801545,
 6266.696258795379,
 6878.086652550984,
 6931.858192432964,
 7078.810705196177,
 7134.980939007476,
 7333.421029778667,
 10622.235357964913]

In [106]:
y_pred = knn.predict(X_test[0].reshape(1,-1))

In [107]:
y_pred

array([1])

In [113]:
y_

15    1
12    1
14    1
3     2
2     2
Name: player type, dtype: int64